### PR TITLE
Orca support

### PR DESCRIPTION
**Pull request by hl2500**
Added support for ORCA single point energy files

### CODE REVIEW

**Comment by njzjz** [comment]
@CodiumAI-Agent /review --pr_reviewer.inline_code_comments=true

**Review by njzjz — APPROVED** [review]
Looks good to me

**Comment by wanghan-iapcm** [comment]
@njzjz shall we remove the supported format table from the README and relies only on the automated format doc?

**Comment by njzjz** [comment]
> @njzjz shall we remove the supported format table from the README and relies only on the automated format doc? 

I agree. Indeed, we also need to merge other parts.

**Pull request merged**
