### PR TITLE
fix: reuse regular methods for deepmd/mixed

### PR DESCRIPTION
**Pull request by njzjz**
## Summary by CodeRabbit

- **New Features**
	- Streamlined data loading process with improved handling of atom types.
	- Enhanced modularization in data dumping, reducing complexity and improving maintainability.
	- Added a new test for verifying data conversion and loading processes for mixed format systems.

- **Bug Fixes**
	- Improved clarity and efficiency in processing atom names and counts.

### CODE REVIEW

**Review by wanghan-iapcm — COMMENTED** [review]
add a UT for customized data type?

**Comment by njzjz** [comment]
It seems I didn't push to my repo due to a mistake.

**Comment by wanghan-iapcm** [comment]
more complete tests by PR #705 and #706

**Review by iProzd — APPROVED** [review]

**Comment by njzjz** [comment]
> add a UT for customized data type?

Done.

**Review by wanghan-iapcm — APPROVED** [review]

**Pull request merged**
