### PR TITLE
Rewrite abacus interface on devel branch; add unites for qe/pw/scf's crystal unit atomic positions read in.

### PR DESCRIPTION
**Pull request by Liu-RX**
Rewrote abacus interface based on devel branch;
added unittest for qe/pw/scf's crystal unit atomic positions read in.

### CODE REVIEW

**Comment by njzjz** [comment]
it’s better to remove .DS_Store

**Comment by Liu-RX** [comment]
> it’s better to remove .DS_Store
> […](#)

Got that! I will remove the file next time.

**Comment by amcadmus** [comment]
> 
> 
> > it’s better to remove .DS_Store
> > […](#)
> 
> Got that! I will remove the file next time.

Please remove the file then I will merge this PR.

**Comment by Liu-RX** [comment]
> > > it’s better to remove .DS_Store
> > > […](#)
> > 
> > 
> > Got that! I will remove the file next time.
> 
> Please remove the file then I will merge this PR.

Sorry for the delay. I didn't notice the reply last week. I have already deleted the .DS_Store files and recommitted.

**Comment by amcadmus** [comment]
Please resolve the conflict.

**Comment by Liu-RX** [comment]
> Please resolve the conflict.

Already resolved the conflict.

**Pull request merged**
